# Generated by Django 4.1.7 on 2023-03-10 13:58

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filepath', models.FileField(upload_to=api.models.create_file_name, verbose_name='Путь к файлу')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Название файла в системе')),
                ('upload_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='FilesDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(verbose_name='id записи в файле')),
                ('company', models.CharField(max_length=256, verbose_name='Название компании')),
                ('date', models.DateTimeField(verbose_name='Первая дата')),
                ('fact_qliq_data1', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Фактические данные по Qliq за первую дату')),
                ('fact_qliq_data2', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Фактические данные по Qliq за вторую дату')),
                ('fact_qoil_data1', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Фактические данные по Qoil за первую дату')),
                ('fact_qoil_data2', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Фактические данные по Qoil за вторую дату')),
                ('forecast_qliq_data1', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Прогнозируемые данные по Qliq за первую дату')),
                ('forecast_qliq_data2', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Прогнозируемые данные по Qliq за вторую дату')),
                ('forecast_qoil_data1', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Прогнозируемые данные по Qoil за первую дату')),
                ('forecast_qoil_data2', models.DecimalField(decimal_places=0, max_digits=256, verbose_name='Прогнозируемые данные по Qoil за вторую дату')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.filemodel', verbose_name='Загруженный файл')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
